# ABSEApp
# Autogenerated from man page /usr/share/man/man1/ABSEApp.1
complete -c ABSEApp -s a --description 'Description of -a flag.'
complete -c ABSEApp -s b --description 'Description of -b flag \\" Ends the list Pp .'

