# actool
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/usr/share/man/man1/actool.1
complete -c actool -l write --description 'Write the resulting asset catalog to the specified  path.'
complete -c actool -l output-format --description 'By default, actool provides output in the form of an XML property list.'
complete -c actool -l compile --description 'Compile the input file and writes the output to the specified path.'
complete -c actool -l output-partial-info-plist --description 'Emit a plist to path that contains keys and values to include in an applicati…'
complete -c actool -l app-icon --description 'Can be combined with --compile to select an app icon to compile to the output…'
complete -c actool -l launch-image --description 'Can be combined with --compile to select a launch image to compile to the out…'
complete -c actool -l platform --description 'Specifies the target platform to compile for.'
complete -c actool -l minimum-deployment-target --description 'Specifies the minimum deployment target to compile for.'
complete -c actool -l target-device --description 'Specifies the target device to compile for, and may be passed multiple times.'
complete -c actool -l print-contents --description 'Include a listing of the catalog\'s content in the output. PP .'
complete -c actool -l warnings --description 'Include document warning messages in actool\'s plist output.'
complete -c actool -l errors --description 'Include document error messages in actool\'s plist output.'
complete -c actool -l notices --description 'Include document notice messages in actool\'s plist output.'
complete -c actool -l version --description 'Print the version of actool.'

