# amlint
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/usr/share/man/man1/amlint.1
complete -c amlint -s H --description 'Print the filename for each error or warning.'
complete -c amlint -s h --description 'Suppress the prefixing of filenames when multiple actions are checked.'
complete -c amlint -s S --description 'For each action, write a summary line indicating how many errors and warnings…'
complete -c amlint -s s --description 'As S, but skips the summary line for actions with no errors or warnings.'
complete -c amlint -s d --description 'Specify a definition bundle, which specifies custom action input and output t…'
complete -c amlint -s x --description 'Specify a list of errors and warnings to ignore.'

