# ani
# Autogenerated from man page /usr/share/man/man1/ani.1
complete -c ani -l trains --description 'Lists all trains in local cache.'
complete -c ani -l train --description 'Lists all updates for train in local cache.'
complete -c ani -l update --description 'Downloads update.'
complete -c ani -l latest --description 'Downloads the latest image for train.'
complete -c ani -l file -l type --description 'Install an image that is not managed by Apple Net Install.'
complete -c ani -l image --description 'The name of the image to download (e. g.  \'AppleInternal\').'
complete -c ani -l livable: --description '.'
complete -c ani -l livable-with-issues: --description '.'
complete -c ani -l release: --description '.'
complete -c ani -l quicklooks: --description 'We do not only filter for the specified flag, but for everything that is at l…'

