# ansible-doc
# Autogenerated from man page /usr/local/share/man/man1/ansible-doc.1
complete -c ansible-doc -s M -l module-path --description 'the DIRECTORY search path to load modules from.'
complete -c ansible-doc -s s -l snippet --description 'Produce a snippet which can be copied into a playbook for modification, like …'
complete -c ansible-doc -s l -l list --description 'Produce a terse listing of modules and a short description of each.'

