# docsetutil
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/usr/share/man/man1/docsetutil.1
complete -c docsetutil -o localization --description 'Perform the operation using a particular localization in the documentation se…'
complete -c docsetutil -o skip-text --description 'Do not perform the operation for the full-text index.'
complete -c docsetutil -o skip-api --description 'Do not perform the operation for the API index.'
complete -c docsetutil -o node --description 'Perform the operation only on the documents that reside at or below a particu…'
complete -c docsetutil -o verbose --description 'Print out additional information about the operation being performed.'
complete -c docsetutil -o debug --description 'Print out detailed information about the operation being performed, which wil…'
complete -c docsetutil -o fallback --description 'Documentation sets can distribute their content between the installed bundle …'
complete -c docsetutil -o download --description 'If a node uses an absolute URL for its landing page, download that page and i…'
complete -c docsetutil -o query --description 'The string to search for in both the full-text and API index.'
complete -c docsetutil -o text-tree --description 'When set, the text search results are presented using a new hierarchical/tree…'
complete -c docsetutil -o toc-depth --description 'When printing out the table-of-content hierarchy, descend only N levels deep.'
complete -c docsetutil -o text-depth --description 'When printing the files from the full-text index, display the full-text hiera…'
complete -c docsetutil -o output --description 'The path of the archive to create.'
complete -c docsetutil -o signid --description 'Include a digital signature in the archive using the specified identity.'
complete -c docsetutil -o atom --description 'Generate or update an entry about the documentation set in an Atom feed file …'
complete -c docsetutil -o download-url --description 'Use the given URL as the download location of the package in the feed entry.'

