# dprivacytool
# Autogenerated from man page /usr/share/man/man1/dprivacytool.1
complete -c dprivacytool -s a --description 'Description of -a flag.'
complete -c dprivacytool -s b --description 'Description of -b flag \\" Ends the list Pp .'

