# dsymutil
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/share/man/man1/dsymutil.1
complete -c dsymutil -l arch --description 'Link DWARF debug information only for specified CPU architecture types.'
complete -c dsymutil -s h --description 'Display the help documentation for this command.'
complete -c dsymutil -s f --description 'Produce a flat dSYM file.  A \'.'
complete -c dsymutil -s o --description 'Specifies an alternate path to place the . dSYM bundle.'
complete -c dsymutil -l oso-prepend-path --description 'Specifies a path to prepend to all debug symbol object file paths.  Pp.'
complete -c dsymutil -s s --description 'Dumps the symbol table found in executable or object file(s) and exits.  Pp.'
complete -c dsymutil -s t --description 'Specifies the maximum number (n) of simultaneous threads to use when linking …'
complete -c dsymutil -s v --description 'Display the current version and build date of the dsymutil binary.  Pp.'
complete -c dsymutil -l verbose --description 'Display verbose information when linking.  Pp.'
complete -c dsymutil -s u --description 'Update an existing dSYM file to contain the latest accelerator tables and oth…'
complete -c dsymutil -l minimize --description 'When used when creating a dSYM file, this option will suppress the emission o…'

