# git-status
# Autogenerated from man page /usr/local/share/man/man1/git-status.1
complete -c git-status -l ---------------------------------------------------------- --description '# branch. oid <commit> | (initial)        Current commit.  # branch.'
complete -c git-status -l ------------------------------------------------------ --description '<XY>        A 2 character field containing the staged and             unstage…'

