# git-fetch
# Autogenerated from man page /usr/local/share/man/man1/git-fetch.1
complete -c git-fetch -l deepen --description 'Similar to --depth, except it specifies the number of commits from the curren…'
complete -c git-fetch -l shallow-since --description 'Deepen or shorten the history of a shallow repository to include all reachabl…'
complete -c git-fetch -l shallow-exclude --description 'Deepen or shorten the history of a shallow repository to exclude commits reac…'

