# git-diff-index
# Autogenerated from man page /usr/local/share/man/man1/git-diff-index.1
complete -c git-diff-index -l indent-heuristic -l no-indent-heuristic --description 'These are to help debugging and tuning experimental heuristics (which are off…'
complete -c git-diff-index -l line-prefix --description 'Prepend an additional prefix to every line of output.'
complete -c git-diff-index -l ita-invisible-in-index --description 'By default entries added by "git add -N" appear as an existing empty file in …'
complete -c git-diff-index -l 'ita-visible-in-index.' --description 'For more detailed explanation on these common options, see also gitdiffcore(7…'

