# git-clone
# Autogenerated from man page /usr/local/share/man/man1/git-clone.1
complete -c git-clone -l shallow-since --description 'Create a shallow clone with a history after the specified time.'
complete -c git-clone -l shallow-exclude --description 'Create a shallow clone with a history, excluding commits reachable from a spe…'
complete -c git-clone -l reference-if-able --description '.'

