# git-ls-files
# Autogenerated from man page /usr/local/share/man/man1/git-ls-files.1
complete -c git-ls-files -l recurse-submodules --description 'Recursively calls ls-files on each submodule in the repository.'

