# git-annotate
# Autogenerated from man page /usr/local/share/man/man1/git-annotate.1
complete -c git-annotate -l indent-heuristic -l no-indent-heuristic -l compaction-heuristic -l no-compaction-heuristic --description 'These are to help debugging and tuning experimental heuristics (which are off…'

