# git-unpack-objects
# Autogenerated from man page /usr/local/share/man/man1/git-unpack-objects.1
complete -c git-unpack-objects -l max-input-size --description 'Die, if the pack is larger than <size>.'

