# git-relink
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/usr/share/man/man1/git-relink.1
complete -c git-relink -l safe --description 'Stops if two objects with the same hash exist but have different sizes.'

