# git-mergetool
# Autogenerated from man page /usr/local/share/man/man1/git-mergetool.1
complete -c git-mergetool -o 'O<orderfile>' --description 'Process files in the order specified in the <orderfile>, which has one shell …'
complete -c git-mergetool -o 'O/dev/null.' --description '.'

