# git-show
# Autogenerated from man page /usr/local/share/man/man1/git-show.1
complete -c git-show -l indent-heuristic -l no-indent-heuristic --description '.'
complete -c git-show -l line-prefix --description '.'
complete -c git-show -l ita-invisible-in-index --description '.'
complete -c git-show -l 'ita-visible-in-index.' --description 'For more detailed explanation on these common options, see also gitdiffcore(7…'

