# git-cat-file
# Autogenerated from man page /usr/local/share/man/man1/git-cat-file.1
complete -c git-cat-file -l filters --description 'Show the content as converted by the filters configured in the current workin…'
complete -c git-cat-file -l path --description 'For use with --textconv or --filters, to allow specifying an object name and …'

