# git-format-patch
# Autogenerated from man page /usr/local/share/man/man1/git-format-patch.1
complete -c git-format-patch -l indent-heuristic -l no-indent-heuristic --description 'These are to help debugging and tuning experimental heuristics (which are off…'
complete -c git-format-patch -l line-prefix --description 'Prepend an additional prefix to every line of output.'
complete -c git-format-patch -l ita-invisible-in-index --description 'By default entries added by "git add -N" appear as an existing empty file in …'
complete -c git-format-patch -l rfc --description 'Alias for --subject-prefix="RFC PATCH".'
complete -c git-format-patch -l 'ita-visible-in-index.' --description 'For more detailed explanation on these common options, see also gitdiffcore(7…'

