# git-fetch-pack
# Autogenerated from man page /usr/local/share/man/man1/git-fetch-pack.1
complete -c git-fetch-pack -l shallow-since --description 'Deepen or shorten the history of a shallow\\(cqrepository to include all reach…'
complete -c git-fetch-pack -l shallow-exclude --description 'Deepen or shorten the history of a shallow repository to exclude commits reac…'
complete -c git-fetch-pack -l deepen-relative --description 'Argument --depth specifies the number of commits from the current shallow bou…'

