# git-log
# Autogenerated from man page /usr/local/share/man/man1/git-log.1
complete -c git-log -l indent-heuristic -l no-indent-heuristic --description '.'
complete -c git-log -l line-prefix --description '.'
complete -c git-log -l ita-invisible-in-index --description '.'
complete -c git-log -l 'ita-visible-in-index.' --description 'For more detailed explanation on these common options, see also gitdiffcore(7…'

