# gnuclient
# Autogenerated from man page /usr/share/man/man1/gnuclient.1
complete -c gnuclient -o nw --description 'This option makes gnuclient act as a frontend such that emacs can attach to t…'
complete -c gnuclient -o display -l display --description 'If this option is given or the `DISPLAY\' environment variable is set then gnu…'
complete -c gnuclient -s q --description 'This option informs gnuclient to exit once connection has been made with the …'
complete -c gnuclient -s v --description 'When this option is specified gnuclient will request for the specified files …'
complete -c gnuclient -s l --description 'Tell Emacs to load the specified library.'
complete -c gnuclient -o batch --description 'Tell Emacs not to open any frames.'
complete -c gnuclient -s f --description 'Make Emacs execute the lisp function.'
complete -c gnuclient -o eval --description 'Make Emacs execute the lisp form.'
complete -c gnuclient -s h --description 'Used only with Internet-domain sockets, this option specifies the host machin…'
complete -c gnuclient -s p --description 'Used only with Internet-domain sockets, this option specifies the service por…'
complete -c gnuclient -s r --description 'Used only with Internet-domain sockets, the pathname argument may be needed t…'

