# hidutil
# Autogenerated from man page /usr/share/man/man1/hidutil.1
complete -c hidutil -s o --description 'output to file [default: stdout].'
complete -c hidutil -s f --description 'display data in specified format (xml or text) [default: xml] El property Ar …'
complete -c hidutil -l set --description 'Get property with key (where key is string value).'
complete -c hidutil -l get --description 'Set property (key/value pair JSON style dictionary).'
complete -c hidutil -l filter --description 'Filter services by properties (key/value pair JSON style dictionary) El list …'

