# mkdep
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/share/man/man1/mkdep.1
complete -c mkdep -s a --description 'Append to the output file, so that multiple mkdep Ns \'s may be run from a sin…'
complete -c mkdep -s f --description 'Write the include file dependencies to file, instead of the default ``.'
complete -c mkdep -s p --description 'Cause mkdep to produce dependencies of the form: -literal -offset indent prog…'

