# mysql
# Autogenerated from man page /usr/local/share/man/man1/mysql.server.1
complete -c mysql -l basedir --description '.'
complete -c mysql -l datadir --description '.'
complete -c mysql -l pid-file --description '.'
complete -c mysql -l service-startup-timeout --description '.'

