# mysql_ssl_rsa_setup
# Autogenerated from man page /usr/local/share/man/man1/mysql_ssl_rsa_setup.1
complete -c mysql_ssl_rsa_setup -l datadir --description 'to specify where to create the files, and.'
complete -c mysql_ssl_rsa_setup -l verbose --description 'to see the openssl commands that mysql_ssl_rsa_setup executes.'
complete -c mysql_ssl_rsa_setup -l 'ssl.' --description '.'
complete -c mysql_ssl_rsa_setup -l ssl-ca --description '.'
complete -c mysql_ssl_rsa_setup -l ssl-cert --description '.'
complete -c mysql_ssl_rsa_setup -l ssl-key --description 'options at startup to name the ca. pem, server-cert. pem, and server-key.'
complete -c mysql_ssl_rsa_setup -l ssl --description 'on the command line to use SSL for the connection.'
complete -c mysql_ssl_rsa_setup -l help --description '?.'
complete -c mysql_ssl_rsa_setup -l suffix --description '.'
complete -c mysql_ssl_rsa_setup -l uid --description '.'
complete -c mysql_ssl_rsa_setup -s v --description '.'
complete -c mysql_ssl_rsa_setup -l version --description '.'
complete -c mysql_ssl_rsa_setup -s V --description '.'

