# ncal
# Autogenerated from man page /usr/share/man/man1/ncal.1
complete -c ncal -s J --description 'Display Julian Calendar, if combined with the e option, display date of easte…'
complete -c ncal -s e --description 'Display date of easter (for western churches).'
complete -c ncal -s j --description 'Display Julian days (days one-based, numbered from January 1).'
complete -c ncal -s m --description 'Display the specified month.'
complete -c ncal -s o --description 'Display date of orthodox easter (Greek and Russian Orthodox Churches).'
complete -c ncal -s p --description 'Print the country codes and switching days from Julian to Gregorian Calendar …'
complete -c ncal -s s --description 'Assume the switch from Julian to Gregorian Calendar at the date associated wi…'
complete -c ncal -s w --description 'Print the number of the week below each week column.'
complete -c ncal -s y --description 'Display a calendar for the specified year.'

