# newfs_apfs
# Autogenerated from man page /usr/share/man/man8/newfs_apfs.8
complete -c newfs_apfs -s b --description 'The block size of the container.'
complete -c newfs_apfs -s o --description 'Additional (undocumented) formatting options.'
complete -c newfs_apfs -s i --description 'Creates a case-insensitive APFS volume.'
complete -c newfs_apfs -s q --description 'Places a quota, or upper limit, on the size of the volume.'
complete -c newfs_apfs -s r --description 'Reserves an amount of space for this volume.'
complete -c newfs_apfs -s s --description 'The fixed size of the volume.'
complete -c newfs_apfs -s v --description 'The name of the volume.  The default is untitled.'
complete -c newfs_apfs -s A --description 'Add a volume to an existing container.'
complete -c newfs_apfs -s C --description 'Create a container only, with no volume.'
complete -c newfs_apfs -s E --description 'Make the volume effaceable ; all its data and metadata will be encrypted with…'
complete -c newfs_apfs -s P --description 'Enable per-file encryption content protection on the volume.'
complete -c newfs_apfs -s R --description 'Set the OS role of the volume within the container.'

