# npm-install
# Autogenerated from man page /usr/local/share/man/man1/npm-install.1
complete -c npm-install -s S -l save: --description 'o 2.'
complete -c npm-install -s D -l save-dev: --description 'o 2.'
complete -c npm-install -s O -l save-optional: --description 'When using any of the above options to save dependencies to your package.'
complete -c npm-install -s E -l save-exact: --description 'exact version rather than using npm\'s default semver range operator.  o 2.'
complete -c npm-install -s B -l save-bundle: --description 'Further, if you have an npm-shrinkwrap. json then it will be updated as well.'

