# nsupdate
# Autogenerated from man page /usr/share/man/man1/nsupdate.1
complete -c nsupdate -s d --description 'option makes nsupdate operate in debug mode.'
complete -c nsupdate -s D --description 'option makes nsupdate report additional debugging information to.'
complete -c nsupdate -o 'd.' --description '.'
complete -c nsupdate -s L --description 'option with an integer argument of zero or higher sets the logging debug leve…'
complete -c nsupdate -s g --description 'flag.'
complete -c nsupdate -s o --description 'flag.'
complete -c nsupdate -s y --description 'or.'
complete -c nsupdate -s k --description 'option to provide the shared secret needed to generate a TSIG record for auth…'
complete -c nsupdate -s l --description 'flag.'
complete -c nsupdate -s v --description 'option makes nsupdate use a TCP connection.'
complete -c nsupdate -s p --description 'sets the default port number to use for connections to a name server.'
complete -c nsupdate -s t --description 'option sets the maximum time an update request can take before it is aborted.'
complete -c nsupdate -s u --description 'option sets the UDP retry interval.  The default is 3 seconds.'
complete -c nsupdate -s r --description 'option sets the number of UDP retries.  The default is 3.'
complete -c nsupdate -s R --description 'option specifies a source of randomness.'
complete -c nsupdate -o 'k.' --description 'gsstsig.'

