# parsec_tool
# Autogenerated from man page /usr/share/man/man1/parsec_tool.1
complete -c parsec_tool -s a --description 'Description of -a flag.'
complete -c parsec_tool -s b --description 'Description of -b flag \\" Ends the list Pp .'

