# ptf_validator
# Autogenerated from man page /usr/share/man/man1/ptf_validator.1
complete -c ptf_validator -s a --description 'Description of -a flag.'
complete -c ptf_validator -s b --description 'Description of -b flag \\" Ends the list Pp .'

