# replace
# Autogenerated from man page /usr/local/share/man/man1/replace.1
complete -c replace -s '?' --description '.'
complete -c replace -s I --description '.'
complete -c replace -o '#debug_options' --description '.'
complete -c replace -s s --description '.'
complete -c replace -s v --description '.'
complete -c replace -s V --description '.'

