# safaridriver
# Autogenerated from man page /usr/share/man/man1/safaridriver.1
complete -c safaridriver -s p --description 'Specifies the port on which the HTTP server should listen for incoming connec…'

