# sysdiagnose
# Autogenerated from man page /usr/share/man/man1/sysdiagnose.1
complete -c sysdiagnose -s h --description 'Display help.'
complete -c sysdiagnose -s f --description 'Specify the directory where the results will be stored.'
complete -c sysdiagnose -s A --description 'Specify the name of the archive created in the results directory.'
complete -c sysdiagnose -s q --description 'Skip footprint.'
complete -c sysdiagnose -s b --description 'Do not show the resulting archive in a Finder window upon completion.'
complete -c sysdiagnose -s p --description 'Request only time-sensitive data to be collected (performance issues).'
complete -c sysdiagnose -s d --description 'Request only log data to be collected (historical issues).'
complete -c sysdiagnose -s X --description 'Run all diagnostics with no timeout.'

