# tailspind
# Autogenerated from man page /usr/share/man/man1/tailspind.1
complete -c tailspind -s r --description 'Include a key in the tailspin file indicating why it was saved.'
complete -c tailspind -s l --description 'Limit the data in tailspin file to that of the last num-seconds.'
complete -c tailspind -s n --description 'Save tailspin file without symbolicating.'
complete -c tailspind -s v --description 'Print layout information of tailspin file.'

