# xcsbridge
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/usr/share/man/man1/xcsbridge.1
complete -c xcsbridge -l format --description 'Specifies the output format for the blueprint, which must be one of: json (a …'
complete -c xcsbridge -l with-anonymous-urls --description 'If passed, the source control URLs will be stripped of username and password …'
complete -c xcsbridge -l with-auth --description 'If passed, the blueprint will contain authentication information for the incl…'
complete -c xcsbridge -l no-auth-strategies --description 'If passed, the blueprint will not contain information on authentication strat…'
complete -c xcsbridge -l no-required-optional --description 'If passed, the blueprint will not contain information on whether each reposit…'
complete -c xcsbridge -l no-branches --description 'If passed, the blueprint will not contain branch/subpath information for each…'
complete -c xcsbridge -l no-special-folder-information --description 'If passed, the blueprint will not contain information on (for example, in Sub…'
complete -c xcsbridge -l with-favorites --description 'If passed, the blueprint will contain information on whether each repository …'
complete -c xcsbridge -l legacy --description 'If passed, all other options (besides --format) will be ignored, and xcsbridg…'

